version: '3.7'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    ports:
      - 15432:5432
    environment: 
      POSTGRES_PASSWORD: "passabc"
      PGDATA: /var/lib/postgresql/data/pgdata 
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      postgres_network:
        aliases:
          - postgres_host
volumes:
  pgdata: {}
networks:
  postgres_network:
    name: postgres_network
    driver: bridge
